apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notification-frontend
  namespace: notification-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: notification-frontend
